default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: teamsnap_app_development
test:
  <<: *default
  database: teamsnap_app_test
production:
  <<: *default
  database: teamsnap_app_production
  username: teamsnap_app
  password: <%= ENV['TEAMSNAP_APP_DATABASE_PASSWORD'] %>
